### ISSUE TITLE
With Elasticsearch 5, indexing domain feed fails

### ISSUE THREAD

**Issue by ninSmith** [CERT-BDF/Hippocampe#13]
```
2017-01-10 18:38:24,957 :: services.modules.shadowbook.processFeed :: ERROR :: processFeed.main failed for domain.conf, no idea where it came from
Traceback (most recent call last):
  File "/home/dc/dev/Hippocampe/core/services/modules/shadowbook/processFeed.py", line 67, in main
    resMsearch = searchIntel.littleMsearch(source.coreIntelligence, source.typeNameESIntel, parsedPage)
  File "/home/dc/dev/Hippocampe/core/services/modules/shadowbook/searchIntel.py", line 72, in littleMsearch
    res = es.msearch(body = req)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 803, in msearch
    raise ValueError("Empty value passed for a required argument 'body'.")
ValueError: Empty value passed for a required argument 'body'.
```

**Comment by ninSmith** [comment]
Does not seem to be reproductible.
