### ISSUE TITLE
Hipposcore in error

### ISSUE THREAD

**Issue by bjuditt** [CERT-BDF/Hippocampe#22]
When i select Hipposcore, i generat an error : 

```
[2017-01-26 15:39:55,685] ERROR in app: Exception on /hippocampe/api/v1.0/hipposcore [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "Hippocampe/core/app.py", line 121, in hipposcoreService
    result = more.main(request.json)
  File "/home/disit/Hippocampe/core/services/more.py", line 54, in main
    queue.put(pool.map(tellMeMore, chunks))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
KeyError: 'type'

```

**Comment by bjuditt** [comment]
I was too fast ! It was necessary to specify the type of data.
It's all for my.
Have a great day !!
