### ISSUE TITLE
Can't seem to get the docker running 

### ISSUE THREAD

**Issue by kx499** [CERT-BDF/Hippocampe#28]
I'm, not very familiar with dockers, but wanted to give this a quick spin. I created a ubuntu VM, allocated 25GB disk, 2GB memory and installed docker. I git pulled and created the docker via the instructions.

When I run this : curl -XGET localhost:5000/hippocampe/api/v1.0/shadowbook

I get  a 500 and stderr/stdout shows this in the image. I can't find any ES logs, but it appears to be running :
[2017-02-05 19:27:40,138][INFO ][node                     ] [Adam II] started
[2017-02-05 19:27:40,178][INFO ][gateway                  ] [Adam II] recovered [0] indices into cluster_state
[2017-02-05 19:28:07,903][INFO ][cluster.metadata         ] [Adam II] [hippocampe] creating index, cause [api], templates [], shards [5]/[1], mappings []
[2017-02-05 19:28:08,322][DEBUG][action.admin.indices.mapping.put] [Adam II] failed to put mappings on indices [[hippocampe]], type [jobs]
org.elasticsearch.index.mapper.MapperParsingException: No handler for type [keyword] declared on field [status]
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:288)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:214)
        at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:136)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:211)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:192)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:449)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$4.execute(MetaDataMappingService.java:505)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:204)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:167)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by kx499** [comment]
I opted to just install on the ES box. Nothing additional needed.

**Comment by markusza** [comment]
I had the same issue, following the documentation. 

I had to change Dockerfile and the docker-entrypoint file.

**Dockerfile**  
changed `FROM elasticsearch:1.7` to 
`FROM elasticsearch:5.1`

**docker-entrypoint**
removed 
```
/docker-entrypoint.sh elasticsearch \
	-Des.script.inline=on \
	-Des.script.indexed=on \
	-Des.threadpool.search.type=fixed \
	-Des.threadpool.search.size=20 \
	-Des.threadpool.search.queue_size=10000 \
	-Des.threadpool.search.type=cached &
```
to
`/docker-entrypoint.sh elasticsearch &`

**Comment by ninSmith** [comment]
Dear @markusza,

Thank for your comment.

For your information, the docker process has been updated in the develop branch to include Hippocampe and Elasticsearch thanks to docker-compose.

Have a look at https://github.com/CERT-BDF/Hippocampe/blob/develop/docs/install_guide.md#docker

Thx
