### ISSUE TITLE
Shadowbook not running, throws 500 error to web server

### ISSUE THREAD

**Issue by jmckinlay** [CERT-BDF/Hippocampe#38]
### Request Type
Bug

### Work Environment

Ubuntu, 1604 Server
Hippocampe current
Python env 2.7.12
PIP 9.0.1

### Problem Description
Can anyone help with the following error, same problem running command line or service in nginx

[2017-06-09 12:58:17,951] ERROR in app: Exception on /hippocampe/api/v1.0/shadowbook [GET]                                                        
Traceback (most recent call last):                                                                                                                
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app                                                              
    response = self.full_dispatch_request()                                                                                                       
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request                                                 
    rv = self.handle_user_exception(e)                                                                                                            
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception                                                 
    reraise(exc_type, exc_value, tb)                                                                                                              
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request                                                 
    rv = self.dispatch_request()                                                                                                                  
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request                                                      
    return self.view_functions[rule.endpoint](**req.view_args)                                                                                    
  File "./app.py", line 168, in shadowbookService                                                                                                 
    if 'error' in reportJob:                                                                                                                      
TypeError: argument of type 'NoneType' is not iterable

**Comment by jmckinlay** [comment]
this is same as Problems with ES2.4.5 with Hippocampe #34
