### ISSUE TITLE
Error retrieving feeds: illegal_argument_exception 

### ISSUE THREAD

**Issue by norgalades** [CERT-BDF/Hippocampe#45]
Hi, I'm running into troubles while retrieving feeds... 
I have installed hippocampe some days ago. 
I've configured hippocampe to run as a service. When I started it and everything went ok, but when I run shadowbook and then I checked the results, I got these errors:

TransportError(400, u'illegal_argument_exception', u'Mapper for [description] conflicts with existing mapping in other types:\\n[mapper [description] is used by multiple types. Set update_all_types to true to update [fielddata] across all types.]')

### Request Type
Possible Bug / Problem 

### Work Environment
Ubuntu 16.04
Hippocampe version installed: commit ce75aae3f8209dbce3945962ec6f948611ee9c4d
Elasticsearch: 5.6.2

### Complementary information
Partial output for the command: **curl -GET http://localhost:80/hippocampe/api/v1.0/jobs**

  "openphish_URL.conf": {
    "activated": true,
    "error": [
      "TransportError(400, u'illegal_argument_exception', u'Mapper for [description] conflicts with existing mapping in other types:\\n[mapper [description] is used by multiple types. Set update_all_types to true to update [fielddata] across all types.]')"
    ],
    "link": "https://openphish.com/feed.txt",
    "nbFailed": 0,
    "nbIndex": 0,
    "nbNew": 0,
    "nbUpdate": 0
  },
  "phishtank_URL.conf": {
    "activated": true,
    "error": [
      "TransportError(400, u'illegal_argument_exception', u'Mapper for [description] conflicts with existing mapping in other types:\\n[mapper [description] is used by multiple types. Set update_all_types to true to update [fielddata] across all types.]')"
    ],
    "link": "http://data.phishtank.com/data/online-valid.csv",
    "nbFailed": 0,
    "nbIndex": 0,
    "nbNew": 0,
    "nbUpdate": 0
  },

**hippocampe's log is saying:**

2017-10-17 10:57:40,063 :: services.modules.shadowbook.processFeed :: INFO :: processFeed.main for binarydefense_IP.conf end
2017-10-17 10:57:40,063 :: services.modules.shadowbook.processFeed :: INFO :: processFeed.main launched for ET_IP.conf
2017-10-17 10:57:40,065 :: services.modules.shadowbook.objects.Source :: INFO :: Source.isActive starts
2017-10-17 10:57:40,065 :: services.modules.shadowbook.objects.Source :: INFO :: E scenario
2017-10-17 10:57:40,078 :: services.modules.shadowbook.processFeed :: ERROR :: processFeed.main failed for ET_IP.conf, no idea where it came from
Traceback (most recent call last):
File "./services/modules/shadowbook/processFeed.py", line 50, in main
source.indexSourceInES()
File "./services/modules/shadowbook/objects/Source.py", line 131, in indexSourceInES
indexSource.createIndexSource()
File "./services/modules/shadowbook/objects/IndexSource.py", line 80, in createIndexSource
self.create()
File "./services/modules/shadowbook/objects/Index.py", line 49, in create
indexES.put_mapping(doc_type = self.typeNameES, body = self.docMapping)
File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
return func(*args, params=params, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 282, in put_mapping
'_mapping', doc_type), params=params, body=body)
File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 312, in perform_request
status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
self._raise_error(response.status, raw_data)
File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'illegal_argument_exception', u'Mapper for [description] conflicts with existing mapping in other types:\n[mapper [description] is used by multiple types. Set update_all_types to true to update [fielddata] across all types.]')
2017-10-17 10:57:40,078 :: services.modules.shadowbook.processFeed :: INFO :: processFeed.main for ET_IP.conf end
2017-10-17 10:57:40,078 :: services.shadowbook :: INFO :: shadowbook.startJob end
2017-10-17 10:57:40,078 :: services.shadowbook :: INFO :: shadowbook.updateJob launched
2017-10-17 10:57:40,078 :: services.shadowbook :: INFO :: updating with status: done
2017-10-17 10:57:40,115 :: services.shadowbook :: INFO :: shadowbook.updateJob end
2017-10-17 10:57:40,115 :: services.shadowbook :: INFO :: shadowbook.manageJob end
2017-10-17 10:57:56,241 :: services :: INFO :: jobs service requested
2017-10-17 10:57:56,243 :: services.modules.common.ES :: INFO :: ES.checkES launched
2017-10-17 10:57:56,246 :: services.modules.common.ES :: INFO :: ES.checkData launched
2017-10-17 10:57:56,246 :: services.modules.common.ES :: INFO :: ['jobsType']
2017-10-17 10:57:56,250 :: services.modules.common.ES :: INFO :: index hippocampe and type jobs exist
2017-10-17 10:57:56,250 :: services.jobs :: INFO :: jobs.main launched
2017-10-17 10:57:56,255 :: services.jobs :: INFO :: jobs.main end

**curl -PUT http://localhost:9200/hippocampe/_mapping?pretty**
{
  "hippocampe" : {
    "mappings" : {
      "jobs" : {
        "properties" : {
          "duration" : {
            "type" : "float"
          },
          "endTime" : {
            "type" : "date",
            "format" : "basic_date_time_no_millis"
          },
          "report" : {
            "properties" : {
              "ET_IP" : {
                "properties" : {
                  "conf" : {
                    "properties" : {
                      "activated" : {
                        "type" : "boolean"
                      },
                      "error" : {
                        "type" : "text",
                        "fields" : {
                          "keyword" : {
                            "type" : "keyword",
                            "ignore_above" : 256
                          }
                        }
                      },
                      "link" : {
                        "type" : "text",
                        "fields" : {
                          "keyword" : {
                            "type" : "keyword",
                            "ignore_above" : 256
                          }
                        }
                      },
                      "nbFailed" : {
                        "type" : "long"
                      },
                      "nbIndex" : {
                        "type" : "long"
                      },
                      "nbNew" : {
                        "type" : "long"
                      },
                      "nbUpdate" : {
                        "type" : "long"
                      }
                    }
                  }
                }
              },

It seems that ES is complaining about some conflicting mappings... How can I "Set update_all_types to true to update [fielddata] across all types." !?

Thank you :)

**Comment by ninSmith** [comment]
Hi,

Could you confirm me whether or not you have Hippocampe and TheHive using the same ES server ?

Thx

**Comment by norgalades** [comment]
@ninSmith , yes they are using the same ES instance

**Comment by ninSmith** [comment]
@norgalades, could you reach me on gitter ?
I'd like to test something with you.

Thx

**Comment by samsowa** [comment]
Hi guys,
I followed the necessary step and install hippocampe and also installed it as a service. However, it is not working. Below are the logs. Can someone help me?

2019-10-29 02:46:03,406 :: services.modules.common.ES :: INFO :: ES.checkES launched
2019-10-29 02:46:12,170 :: services :: INFO :: sizeByType service requested
2019-10-29 02:46:12,171 :: services.modules.common.ES :: INFO :: ES.checkES launched
2019-10-29 02:46:12,172 :: services :: INFO :: sizeBySources service requested
2019-10-29 02:46:12,172 :: services.modules.common.ES :: INFO :: ES.checkES launched
2019-10-29 02:46:12,180 :: services :: INFO :: type service requested
2019-10-29 02:46:12,180 :: services.modules.common.ES :: INFO :: ES.checkES launched
2019-10-29 02:46:12,188 :: services :: INFO :: monitorSources service requested
2019-10-29 02:46:12,189 :: services.modules.common.ES :: INFO :: ES.checkES launched
2019-10-29 02:46:12,264 :: services.modules.common.ES :: INFO :: ES.checkData launched
2019-10-29 02:46:12,264 :: services.modules.common.ES :: INFO :: []
2019-10-29 02:46:12,299 :: services.modules.common.ES :: INFO :: ES.checkData launched
2019-10-29 02:46:12,299 :: services.modules.common.ES :: INFO :: ['sourceType']
2019-10-29 02:46:12,318 :: services.modules.common.ES :: INFO :: ES.checkData launched
2019-10-29 02:46:12,319 :: services.modules.common.ES :: INFO :: ['sourceType']
2019-10-29 02:46:12,333 :: services.modules.common.ES :: INFO :: ES.checkData launched
2019-10-29 02:46:12,333 :: services.modules.common.ES :: INFO :: ['sourceType']
2019-10-29 02:46:12,382 :: services.modules.common.ES :: INFO :: index hippocampe does not exist
2019-10-29 02:46:12,382 :: services :: ERROR :: no data
2019-10-29 02:46:12,392 :: services.modules.common.ES :: INFO :: index hippocampe does not exist
2019-10-29 02:46:12,392 :: services :: ERROR :: no data
2019-10-29 02:46:12,407 :: services.modules.common.ES :: INFO :: index hippocampe does not exist
2019-10-29 02:46:12,407 :: services :: ERROR :: no data
2019-10-29 02:46:12,431 :: services.modules.common.ES :: INFO :: index hippocampe does not exist
2019-10-29 02:46:12,432 :: services :: ERROR :: no data
2019-10-29 02:46:12,481 :: services :: INFO :: type service requested
2019-10-29 02:46:12,481 :: services.modules.common.ES :: INFO :: ES.checkES launched
2019-10-29 02:46:12,489 :: services.modules.common.ES :: INFO :: ES.checkData launched
2019-10-29 02:46:12,489 :: services.modules.common.ES :: INFO :: []
2019-10-29 02:46:12,504 :: services.modules.common.ES :: INFO :: index hippocampe does not exist
2019-10-29 02:46:12,504 :: services :: ERROR :: no data
2019-10-29 02:46:25,220 :: services :: INFO :: sources service requested
2019-10-29 02:46:25,221 :: services.modules.common.ES :: INFO :: ES.checkES launched
2019-10-29 02:46:25,227 :: services.modules.common.ES :: INFO :: ES.checkData launched
2019-10-29 02:46:25,228 :: services.modules.common.ES :: INFO :: ['sourceType']
2019-10-29 02:46:25,247 :: services.modules.common.ES :: INFO :: index hippocampe does not exist
2019-10-29 02:46:25,248 :: services :: ERROR :: no data
2019-10-29 02:46:27,573 :: services :: INFO :: jobs service requested
2019-10-29 02:46:27,573 :: services.modules.common.ES :: INFO :: ES.checkES launched
2019-10-29 02:46:27,586 :: services.modules.common.ES :: INFO :: ES.checkData launched
2019-10-29 02:46:27,586 :: services.modules.common.ES :: INFO :: ['jobsType']
2019-10-29 02:46:27,599 :: services.modules.common.ES :: INFO :: index hippocampe does not exist
2019-10-29 02:46:27,600 :: services :: ERROR :: no data
2019-10-29 02:46:29,931 :: services :: INFO :: type service requested
2019-10-29 02:46:29,932 :: services.modules.common.ES :: INFO :: ES.checkES launched
2019-10-29 02:46:29,947 :: services.modules.common.ES :: INFO :: ES.checkData launched
2019-10-29 02:46:29,947 :: services.modules.common.ES :: INFO :: []
